/* Hash Key Decryptor */

// Library headers
#include <crypt.h>
#include <stdio.h>
#include <string.h>

// Maximum possible length of the key
#define MAX_KEY_LENGTH 8

// Total characters count in array of characters to use for the search
#define CHARACTERS_COUNT 62

// Possible characters to check for
const char POSSIBLE_CHARACTERS[CHARACTERS_COUNT] = {
  'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
  'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's',
  't', 'u', 'v', 'w', 'x', 'y', 'z',
  '1', '2', '3', '4', '5', '6', '7', '8', '9', '0',
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
  'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S',
  'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
};

// Last Character in array of possible characters
#define LAST_CHARACTER POSSIBLE_CHARACTERS[CHARACTERS_COUNT - 1]

// Function to return the next char from the characters array for the given character
char next_char(char c)
{
  int i;
  // Searches for the given character
  for (i = 0; i < CHARACTERS_COUNT && POSSIBLE_CHARACTERS[i] != c; i++);

  return POSSIBLE_CHARACTERS[i + 1];
}

int main(int argc, char *argv[])
{
  // Iterator
  int i;
  // Starting length of the key to search for
  int len = 1;
  // Flag to check if the next key exists
  int next_key_exists;
  // Character key to encrypt
  char key[MAX_KEY_LENGTH + 1] = "a";
  // This is the hash that we are looking for:
  char hash_to_look_for[14];
  // argv[1] - the known salt that was used to encrypt the key
  strcpy(hash_to_look_for, argv[1]);
  // argv[2] - the hash to look for
  strcat(hash_to_look_for, argv[2]);
  // Variable to hold the hashes generated by searching
  char *hash;
  // Flag to indicate if we have found the key
  int found = 0;

  // Prints the brute forcing process with the current character search
  printf("Brute force for keys with length from 1 to 8\n");
  printf("Possible Characters: a-z, A-Z, 0-9\n");

  do {
    // Encrypts the current key
    hash = crypt(key, argv[1]);
    // Prints the key and hash
    printf("%s %s\n", key, hash);
    // Verifies the hash that we're looking for
    found = (strcmp(hash, hash_to_look_for) == 0);
    // If the hash is not found, generates the next key to check
    if (!found) {
      do {
        // Sets the flag for the next key
        for (i = len - 1; i >= 0 && key[i] == LAST_CHARACTER; i--);
        // Iterates to the next character from the array
        if (i >= 0) {
          key[i] = next_char(key[i]);
          // Changes characters incrementally from possible harters
          for (i++ ; i < len; key[i] = POSSIBLE_CHARACTERS[0], i++);
          // Sets the flag to generate the next key
          next_key_exists = 1;
        // Else, moves to the next length
        } else {
          len++;
          if (len <= MAX_KEY_LENGTH) {
            // Sets the key to one that contains all first characters from the array of possible characters
            for (i = 0; i < len; key[i] = POSSIBLE_CHARACTERS[0], i++);
            // Sets the end of the key to \0 to finish the string
            key[len] = '\0';
            // Sets the flag for the next key
            next_key_exists = 1;
          }
        }
        // Generates the next key while we have not exceeded the maximum length
      } while (len <= MAX_KEY_LENGTH && !next_key_exists);
    }
    // Searches and checks the next key while the key is not found
  } while (!found && next_key_exists);

  // Prints the key if it's found
  if (found) {
    printf("\nKey found - %s\n", key);
  }
  // Else, if the key is not found prints this message
  else
  {
    printf("Sorry, key not found\n");
  }

  return 0;
}